name: Docker Image Push Test

on:
  push:
    branches: [ "main", "release" ]
      
jobs:
  build:
    # PR이 머지된 경우에만 실행
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew


    - name: Run Gradle Build
      run: ./gradlew clean build -PDATABASE_HOST=${{ secrets.DATABASE_HOST }} -PDATABASE_NAME=${{ secrets.DATABASE_NAME }} -PDATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -PDATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

    - name: Configure Docker daemon
      run: |
        echo '{ "insecure-registries": ["${{ secrets.DOCKER_REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json

        sudo systemctl restart docker

    - name: Login to Docker Registry
      run: docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: List directory contents
      run: ls -la

    - name: List contents of build/libs
      run: ls -la ./build/libs/

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY_URL }}/backend:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY_URL }}/backend:latest

    - name: Save image digest
      run: echo "${{ steps.docker_build.outputs.digest }}" > image-digest.txt

    - name: Upload image digest as artifact
      uses: actions/upload-artifact@v2
      with:
        name: image-digest
        path: image-digest.txt

  update-manifest:
    name: Update Kubernetes manifest
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download image digest artifact
        uses: actions/download-artifact@v2
        with:
          name: image-digest
      - name: Update image in Kubernetes manifest
        run: |
          IMAGE_DIGEST=$(cat image-digest.txt)
          
          sed -i "s|image: ${{ secrets.DOCKER_REGISTRY_URL }}/backend@sha256:[a-zA-Z0-9]*|image: ${{ secrets.DOCKER_REGISTRY_URL }}/backend@$IMAGE_DIGEST|g" deploy/deployment.yml
      - name: Commit and push changes
        run: |
          git config --local user.email "tkd8973@gmail.com"
          git config --local user.name "tkd8973"
          git add deploy/deployment.yml
          git commit -m "Update image in Kubernetes manifest"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tkd8973/PICMAP_BACKEND.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}