name: Docker Image Push Test

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
jobs:
  build-and-push:
    # PR이 머지된 경우에만 실행
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew


    - name: Run Gradle Build
      run: ./gradlew clean build -PDATABASE_HOST=${{ secrets.DATABASE_HOST }} -PDATABASE_NAME=${{ secrets.DATABASE_NAME }} -PDATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -PDATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}

    - name: Configure Docker daemon
      run: |
        echo '{ "insecure-registries": ["${{ secrets.DOCKER_REGISTRY_URL }}"] }' | sudo tee /etc/docker/daemon.json

        sudo systemctl restart docker

    - name: Login to Docker Registry
      run: docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: List directory contents
      run: ls -la

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/picturemapping .
        docker push ${{ secrets.DOCKER_REGISTRY_URL }}/picturemapping

      
